### ISSUE TITLE
How do I install this and does it work with Open Project v6.1.5 

### ISSUE THREAD

**Issue by razaqadams** [nietonfir/openproject-gitlab_integration#1]
Hi @nietonfir , Thanks for the nice work. Sorry for asking a lame question. How do I o about implementing this integration (the Readme doesn't say much). I would also like to know if it is compatible with Open Project v 6.1.5? Thank you.

**Comment by nietonfir** [comment]
Hey. Really sorry to disappoint you, but this was only a private research project (back with OpenProject 3 or 4 iirc) that I didn't even bother to commit & push everything. Will mark the as deprecated/abandoned.
